version: '3'
services:
  pg:
    build: ./scripts/
    ports: 
      - "5432:5432"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  api:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - pg